version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7h44er8j5S
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    environment:
      SECRET_KEY: your-secret-key
      DEBUG: "True"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./frontend/build:/app/backend/static
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: >
      sh -c "npm install && npm run build"

  nginx:  # 🔥 ПЕРЕНЕСИ ЭТО СЮДА
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: diploma-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/app/frontend/build
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/media:/app/media

volumes:
  db-data:
